
// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: MIT

import { AboutSlint,VerticalBox } from "std-widgets.slint";

export component AboutPage inherits VerticalBox {
    // title: "About";
    // show-enable-switch: false;
    // description: "Are you curious now? Check out the docs and getting starteds from the Github repository and the website https://slint.dev and try it yourself.";

    AboutSlint {}
}
