import { VerticalBox, StandardListView, Button, LineEdit, HorizontalBox, StandardTableView } from "std-widgets.slint";
import {ChangeEquipament } from "../globals/computer.slint";

export component ChangeUserEquipament inherits VerticalBox {
    HorizontalBox {
        Button {
            text: @tr("save");
            clicked => {
                ChangeEquipament.change_user();
            }
        }

        Button {
            text: @tr("back");
            clicked => {
                ChangeEquipament.change_equipament = false;
            }
        }
    }

    LineEdit {
        accepted => {
            ChangeEquipament.filter_users()
        }
    }

    StandardTableView {
        rows: ChangeEquipament.users;
        current-row-changed(index) => {
            ChangeEquipament.future_user = ChangeEquipament.users[index][3].text;
        }
    }
}
