import { VerticalBox, StandardListView, Button, LineEdit, HorizontalBox, StandardTableView } from "std-widgets.slint";
import {ChangeEquipament, ComputerDetail } from "../globals/computer.slint";

export component ChangeUserEquipament inherits VerticalBox {
    HorizontalBox {
        Button {
            text: @tr("save");
            clicked => {
                ChangeEquipament.change_user();
            }
        }

        Button {
            text: @tr("back");
            clicked => {
                ChangeEquipament.change_equipament = false;
            }
        }
    }

    LineEdit {
        accepted => {
            ChangeEquipament.filter_users()
        }
    }

    StandardTableView {
        rows: ChangeEquipament.users;
        current-row-changed(index) => {
            // debug(ChangeEquipament.users[index][1].text);
            // debug(ChangeEquipament.users[index][0].text);
            // debug(ChangeEquipament.users[index][2].text);
            // debug(ComputerDetail.serial_number);
            ComputerDetail.users_history(ComputerDetail.serial_number);
            ChangeEquipament.future_login = ChangeEquipament.users[index][1].text;
        }
    }
}
