import { StandardTableView, VerticalBox ,Button, LineEdit, ComboBox} from "std-widgets.slint";
import {GlobalCPU} from "../globals/cpu.slint";



export component CPU inherits VerticalBox {
    private property <int> current;
    private property <string> text;
    private property <string> brand:GlobalCPU.brands[0];

    VerticalLayout {
        HorizontalLayout {
            LineEdit{
                edited(actual) => {
                    root.text = actual;
                }
            }
            ComboBox {
                model: GlobalCPU.brands;
                current-value: "";
                selected(actual) => {
                    root.brand = actual;
                }
            }
            Button {text:"add";
                clicked => {
                    GlobalCPU.add_item(root.text,root.brand)
                }
            }
            Button {text:"delete";
            clicked => {
                GlobalCPU.delete_item(GlobalCPU.row_data[root.current][0])
            }
            }
            

        }
        StandardTableView{
            rows: GlobalCPU.row_data;
            current-row-changed(actual) => {
                root.current = actual;
            }

        }
    }

}
