
import { StandardListView, VerticalBox ,Button, Palette, LineEdit, ListView} from "std-widgets.slint";
import {GlobalDepartment} from "../globals/department.slint";


export component Department inherits VerticalBox{
    private property <int> current;
    private property <string> text;
    VerticalLayout {
        HorizontalLayout {
            LineEdit {
                edited(actual)=>{
                    root.text = actual;
                }
            }
            Button {
                text: @tr("add");
                clicked => {
                    GlobalDepartment.add_item(root.text) 
                }
            }
            Button {
                text: @tr("delete");
                clicked => {
                    GlobalDepartment.delete_item(GlobalDepartment.row_data[root.current])
                }
            }
        }
     StandardListView{
        model: GlobalDepartment.row_data;
            current-item-changed(actual) => {
                root.current = actual;
        }           

    }
}

}

