import { StandardTableView, VerticalBox ,Button, LineEdit, ComboBox} from "std-widgets.slint";
import {GlobalGPU} from "../globals/gpu.slint";



export component GPU inherits VerticalBox {
    private property <int> current;
    private property <string> text;
    private property <string> brand:GlobalGPU.brands[0];
    VerticalLayout {
        HorizontalLayout {
            LineEdit {
                edited(actual) => {
                    root.text = actual;
                }
            }

            ComboBox {
                model: GlobalGPU.brands;
                current-value: "";
                selected(actual) => {
                    root.brand = actual;
                }
            }

            Button {
                text: "add";
                clicked => {
                    GlobalGPU.add_item(root.text,root.brand)
                }
            }

            Button {
                text: "delete";
                clicked => {
                    GlobalGPU.delete_item(GlobalGPU.row_data[root.current][0])
                }
            }
        }

        StandardTableView {
            rows: GlobalGPU.row_data;
            current-row-changed(actual) => {
                root.current = actual;
            }
        }
    }
}
