import { StandardTableView, VerticalBox ,Button, Palette, LineEdit, ComboBox, ScrollView, HorizontalBox} from "std-widgets.slint";
import { Users,  UserDetail } from "../globals/users.slint";


component CreateUser inherits VerticalBox {
    private property <length> height_itens:50px;
    private property <length> width_itens:100px;
    VerticalBox {
        HorizontalLayout {
            Button {
                height: 50px;
                text: "save";
                clicked => {
                    UserDetail.create();
                    Users.create_user = false;
                }
            }

            Button {
                height: 50px;
                text: "back";
                clicked => {
                    Users.create_user = false
                }
            }
        }

        ScrollView {
            GridLayout {
                Text {
                    text: "name";
                }

                LineEdit {
                    edited(str) => {
                        UserDetail.name = str
                    }
                    height: root.height_itens;
                }

                Text {
                    width: root.width_itens;
                    text: "department";
                    row: 1;
                }

                ComboBox {
                    model: UserDetail.departments;
                    height: root.height_itens;
                    selected(actual) => {
                        UserDetail.department = actual;
                    }
                }

                Text {
                    text: "document";
                    row: 2;
                }

                LineEdit {
                    edited(str) => {
                        UserDetail.document = str
                    }
                    height: root.height_itens;
                }

                Text {
                    text: "email";
                    row: 3;
                }

                LineEdit {
                    edited(str) => {
                        UserDetail.email = str
                    }
                    height: root.height_itens;
                }

                Text {
                    text: "login";
                    row: 4;
                }

                LineEdit {
                    edited(str) => {
                        UserDetail.login = str
                    }
                    height: 50px;
                }

                Text {
                    text: "extension";
                    row: 5;
                }

                LineEdit {
                    edited(str) => {
                        UserDetail.extension = str
                    }
                    height: root.height_itens;
                }

                Text {
                    text: @tr("phone_number");
                    row: 6;
                }

                LineEdit {
                    edited(str) => {
                        UserDetail.phone_number = str
                    }
                    height: root.height_itens;
                }
            }
        }
    }
}

component User inherits VerticalBox {
    in-out property <string> name;
    VerticalLayout {
        alignment: LayoutAlignment.space-between;
        HorizontalLayout {
            Button {
                text: "salvar";
                clicked => {
                    UserDetail.save();
                    UserDetail.update();
                }
            }

            HorizontalLayout {
                alignment: LayoutAlignment.end;
                Button {
                    text: "voltar";
                    height: 50px;
                    clicked => {
                        Users.selected_user = false;
                    }
                }
            }
        }

        GridLayout {
            Text {
                text: "name";
            }

            LineEdit {
                text: UserDetail.name;
                edited(str) => {
                    UserDetail.name = str
                }
            }

            Text {
                text: "login";
                row: 1;
            }

            LineEdit {
                text: UserDetail.login;
                enabled: false;
            }

            Text {
                text: "department";
                row: 2;
            }

            ComboBox {
                model: UserDetail.departments;
                selected(value) => {
                    UserDetail.department = value;
                }
            }

            Text {
                text: "email";
                row: 3;
            }

            LineEdit {
                text: UserDetail.email;
            }
        }

        spacing: 30px;
        StandardTableView {
            columns: [
                { title:"serialn" },
                { title:"brand" },
                { title:"model" },
                { title:"initial date" },
                { title:"final date" }
            ];
            rows: UserDetail.row-data;
        }
    }
}

component ShowUser inherits VerticalBox {
    VerticalLayout {
        HorizontalLayout {
            Button {
                text: "create user";
                clicked => {
                    Users.create_user = true;
                }
            }
        }

        StandardTableView {
            columns: [{ title: "name" }, { title: "login" }, { title: "email" }];
            rows: Users.row-data;
            row-pointer-event(index, event, _) => {
                if event.button == PointerEventButton.left {
                    Users.current_user = Users.row_data[index][0].text;
                    UserDetail.name = Users.row_data[index][0].text;
                    UserDetail.login = Users.row_data[index][1].text;
                    UserDetail.email = Users.row_data[index][2].text;
                    Users.selected_user = true;
                }
            }
        }
    }
}

export component UserList inherits VerticalBox {
    if !Users.selected_user && !Users.create_user: ShowUser { }
    if !Users.selected_user && Users.create_user: CreateUser { }
    if Users.selected_user: User {
        name: Users.current_user;
    }
}
