
// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: MIT

import { UserList,Users ,UserDetail} from "list_users.slint";
export { UserList,Users ,UserDetail}

import  { ComputerList,Computers,ComputerDetail} from "list_computers.slint";
export { ComputerList,Computers,ComputerDetail }


import { ChangeEquipament } from "change_user_equipament.slint";
export { ChangeEquipament }

