
import { StandardListView, VerticalBox ,Button, Palette, LineEdit, ListView} from "std-widgets.slint";
import {GlobalPhone} from "../globals/phone_number.slint";


export component PhoneNumbers inherits VerticalBox {
    private property <int> current;
    private property <string> text;
    VerticalLayout {
        HorizontalLayout {
            LineEdit {
                edited(actual) => {
                    root.text = actual;
                }
            }

            Button {
                text: @tr("add");
                clicked => {
                    GlobalPhone.add_item(root.text)
                }
            }

            Button {
                text: @tr("delete");
                clicked => {
                    GlobalPhone.delete_item(GlobalPhone.row_data[root.current])
                }
            }
        }

        StandardListView {
            model: GlobalPhone.row_data;
            current-item-changed(actual) => {
                root.current = actual;
            }
        }
    }
}
