[package]
name = "simple_inventary"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.79"
chrono = "0.4.37"
directories = "5.0.1"
slint = "1.9.2"
sqlx = { version = "0.8.1", features = ["sqlite", "runtime-tokio"]}
tokio = { version = "1.36.0", features = ["rt-multi-thread", "rt", "macros"] }

[build-dependencies]
slint-build = "1.9.2"

[profile.release]
strip=true
opt-level="z"
lto=true

[profile.dev.build-override]
opt-level = 2
