import {ChangeEquipament,Computers, ComputerDetail} from "computer.slint";
export {ChangeEquipament,Computers, ComputerDetail}


import {Users,UserDetail} from "users.slint";
export {Users,UserDetail}

import {GlobalBrand} from "brand.slint";
export {GlobalBrand}

import {GlobalDepartment} from "department.slint";
export {GlobalDepartment}

import {GlobalCPU} from "cpu.slint";
export {GlobalCPU}

import {GlobalGPU} from "gpu.slint";
export {GlobalGPU}

import {GlobalRole} from "role.slint";
export {GlobalRole}

import {GlobalPhone} from "phone_number.slint";
export {GlobalPhone}


import {GlobalEquipamentModel,GlobalEquipamentModelDetail} from "equipament_model.slint";
export {GlobalEquipamentModel, GlobalEquipamentModelDetail }
