import   {ChangeEquipament} from "computer.slint";


export global Users {
    in property <[[StandardListViewItem]]> row_data: [
        [{ text:"name 1" }, { text:"login 1" }, { text:"email 1" }],
        [{ text:"name 2" }, { text:"email 2" }, { text:"email 2" }],
        [{ text:"name 3" }, { text:"login 3" }, { text:"email 3" }],
    ];
    in property <bool> create_user:false;
    in property <bool> selected_user: false;
    in property <string> current_user;
}

export global UserDetail {
    in property <[[StandardListViewItem]]> row_data:[
        [
            { text:"dlsajdl" },
            { text:"dell" },
            { text:"inspiron" },
            { text:"2023-12-31" },
            { text:"" }
        ],
        [
            { text:"djslajdl" },
            { text:"asus" },
            { text:"vivobook" },
            { text:"2023-11-31" },
            { text:"" }
        ],
        [
            { text:"ldsjald" },
            { text:"samsung" },
            { text:"book 3" },
            { text:"2023-10-31" },
            { text:"" }
        ],
    ];
    in-out property <[string]> departments:["frota","ti","rh"] ;
    in property <string> department:"" ;
    in property <string> name;
    in property <string> login;
    in property <string> email;
    in property <string> document;
    in property <int> id;
    in property <string> extension;
    in property <string> phone_number;
    callback save();
    callback create();
    callback update();
}
