// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: MIT

import { CheckBox, StandardListView, StyleMetrics } from "std-widgets.slint";
import {  UserList, Users, UserDetail} from "pages/pages.slint";
import { ComputerList,Computers,ComputerDetail } from "pages/pages.slint";
import { SideBar } from "side_bar.slint";
import { ChangeEquipament} from "pages/pages.slint";

export {Users,UserDetail,ChangeEquipament,ComputerDetail,Computers}

export component App inherits Window {
    preferred-width: 1280px;
    preferred-height: 720px;
    title: @tr("Slint Widgets Gallery");

    HorizontalLayout {
        side-bar := SideBar {
            title: @tr("Slint Widgets Gallery");
            model: [
            @tr("Menu" => "Users"),
            @tr("Menu" => "Computers")];
        }

        if(side-bar.current-item == 0) : UserList {}
        if(side-bar.current-item == 1) : ComputerList{}
    }
    }
