// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: MIT

import { CheckBox, StandardListView, StyleMetrics } from "std-widgets.slint";
import {  UserList } from "pages/pages.slint";
import { ComputerList} from "pages/pages.slint";
import { SideBar } from "side_bar.slint";
import { ChangeEquipament,Users,UserDetail,Computers,ComputerDetail,GlobalBrand} from "globals/globals.slint";
import { Brand} from "pages/brand.slint";




export {Users,UserDetail,ChangeEquipament,ComputerDetail,Computers,GlobalBrand}


export component App inherits Window {
    preferred-width: 1280px;
    preferred-height: 720px;
    title: @tr("Slint Widgets Gallery");
    HorizontalLayout {
        side-bar := SideBar {
            title: @tr("Slint Widgets Gallery");
            model: [@tr("Menu" => "Users"), @tr("Menu" => "Computers"), @tr("Menu" => "Brand")];
        }

        if(side-bar.current-item == 0): UserList { }
        if(side-bar.current-item == 1): ComputerList { }
        if(side-bar.current-item == 2): Brand{}
    }
}
